[package]
name = "bili-tui"
version = "0.1.22"
edition = "2024"
description = "A TUI client for Bilibili written in Rust."
license = "MIT"
repository = "https://github.com/vandeefeng/bili-tui"
homepage = "https://github.com/vandeefeng/bili-tui"
readme = "README.md"
keywords = ["bilibili", "tui", "cli", "video", "terminal"]
categories = ["command-line-utilities", "multimedia::video"]

[dependencies]
ratatui = { version = "0.29.0", features = ["all-widgets"] }
crossterm = "0.29.0"
tokio = { version = "1.38.0", features = ["full"] }
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
tui-input = "0.14.0"
url = "2.5.7"
textwrap = "0.16.2"
chrono = "0.4"
dotenv = "0.15"
dirs = "6.0"
md5 = "0.7.0"
